### ISSUE TITLE
More than just scroll

### ISSUE THREAD

**Issue by fregante** [asvd/naturalScroll#3]
Scrolling is only one of the movements that could benefit from being _natural_; perhaps this library could be rewritten as **naturalMove** and let people apply it to any property.

Its API could be:

``` js
naturalMove(start, end);
-> {duration: ..., easingFunction: ...} // from what I understand
```

Once one has those you could just use one of the many many animation libraries

**Comment by asvd** [comment]
This sounds like a subject for a separate library (I have once started working on it, and the animation formulaes have actually been taken from there). Such a library would require more configuration options, and there are already a lot of them on the web. Eventually I came up with this minimal solution covering the particular scrolling-case.
